/**
 * Created by 337547038 on 2018/2/2.
 */
module.exports = {
    index: require('./index'),
    button: require('./button'),
    header: require('./header'),
    input: require('./input'),
    radio: require('./radio'),
    checkbox: require('./checkbox'),
    inputNumber: require('./inputNumber'),
    list: require('./list'),
    switch: require('./switch'),
    textarea: require('./textarea'),
    upload: require('./upload'),
    progress: require('./progress'),
    picker: require('./picker'),
    cityPicker: require('./cityPicker'),
    select: require('./select'),
    datePicker: require('./datePicker'),
    swiper: require('./swiper'),
    formItem: require('./formItem'),
    form: require('./form'),
    dialog: require('./dialog'),
    loading: require('./loading'),
    tabbar: require('./tabbar'),
    tab: require('./tab'),
    badge: require('./badge'),
    pullRefreshLoading: require('./pullRefreshLoading'),
    keyboard: require('./keyboard'),
    test: require('./test'),
}